version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-apache
    ports:
      - "8000:80"  # ✅ پورت واقعی
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # ✅ سرور: دیتا از پروژه به داکر میره
      - ./data:/var/www/html
      - ./php-config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    # user معمولاً در سرور متفاوت است

volumes:
  db_data: